openapi: 3.0.1
info:
  version: 0.1.0
  title: VeChain Thor API
  license:
    name: LGPL 3.0
    url: 'https://www.gnu.org/licenses/lgpl-3.0.en.html'
  description: RESTful API to access VeChain Thor
servers:
  - url: 'http://localhost:8669'
    description: local thor node
tags:
  - name: Account
    description: Access to account objects
  - name: Block
    description: Access to blocks
  - name: Transaction
    description: Access to transactions
paths:
  '/accounts/{address}':
    parameters:
      - $ref: '#/components/parameters/AddressInPath'
      - $ref: '#/components/parameters/RevisionInQuery'
    get:
      tags:
        - Account
      summary: get account object detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    post:
      tags:
        - Account
      summary: perform contract call on account object
      requestBody:
        description: arguments and environment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractCall'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractCallResult'
  '/accounts/{address}/code':
    parameters:
      - $ref: '#/components/parameters/AddressInPath'
      - $ref: '#/components/parameters/RevisionInQuery'
    get:
      tags:
        - Account
      summary: retrieve code of account object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                example:
                  code: >-
                    0x6060604052600080fd00a165627a7a72305820c23d3ae2dc86ad130561a2829d87c7cb8435365492bd1548eb7e7fc0f3632be90029
  '/accounts/{address}/storage/{key}':
    parameters:
      - $ref: '#/components/parameters/AddressInPath'
      - $ref: '#/components/parameters/StorageKeyInPath'
      - $ref: '#/components/parameters/RevisionInQuery'
    get:
      tags:
        - Account
      summary: retrieve storage value of account object for given key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                example:
                  value: >-
                    0x0000000000000000000000000000000000000000000000000000000000000001
  '/accounts/{address}/logs':
    parameters:
      - $ref: '#/components/parameters/AddressInPath'
    post:
      tags:
        - Account
      summary: filter event logs produced by the account object
      parameters:
        - $ref: '#/components/parameters/LogFilterOffsetInQuery'
        - $ref: '#/components/parameters/LogFilterLimitInQuery'
        - $ref: '#/components/parameters/LogFilterOrderInQuery'
      requestBody:
        description: log filter criteria
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FilteredLog'
  '/blocks/{revision}':
    parameters:
      - $ref: '#/components/parameters/RevisionInPath'
    get:
      tags:
        - Block
      summary: 'retrieve block by ID, number, or ''best'' for the latest one'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
  '/transactions/{id}':
    parameters:
      - $ref: '#/components/parameters/TxIDInPath'
    get:
      tags:
        - Transaction
      summary: retrieve transaction by its id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  '/transactions/{id}/receipt':
    parameters:
      - $ref: '#/components/parameters/TxIDInPath'
    get:
      tags:
        - Transaction
      summary: retrieve transaction receipt by transaction ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
  /transactions:
    post:
      tags:
        - Transaction
      summary: send raw transaction
      requestBody:
        description: hex form of encoded transaction
        required: true
        content:
          application/json:
            schema:
              type: string
              example: '0xaabbccddeeff'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                example:
                  id: >-
                    0x4de71f2d588aa8a1ea00fe8312d92966da424d9939a511fc0be81e65fad52af8
components:
  schemas:
    Account:
      properties:
        balance:
          type: string
          description: hex form of token balance
        energy:
          type: string
          description: hex form of remained amount of energy
        hasCode:
          type: boolean
      example:
        balance: '0xde0b6b3a7640000'
        energy: '0xde0b6b3a7640000'
        hasCode: false
    Block:
      properties:
        number:
          type: integer
          format: uint32
          description: number(height) of the block
        id:
          type: string
          description: identifier of the block (bytes32)
        size:
          type: integer
          format: uint32
          description: byte size of the block that is RLP encoded
        parentID:
          type: string
          description: ID of parent block (bytes32)
        timestamp:
          type: integer
          format: uint64
          description: unix timestamp of the block
        gasLimit:
          type: integer
          format: uint64
          description: gas limit of the block
        beneficiary:
          type: string
          description: address of account to receive block reward
        gasUsed:
          type: integer
          format: uint64
        totalScore:
          type: integer
          format: uint64
        txsRoot:
          type: string
          description: root hash of transactions in the block (bytes32)
        stateRoot:
          type: string
          description: root hash of accounts state (bytes32)
        receiptsRoot:
          type: string
          description: root hash of transaction receipts (bytes32)
        signer:
          type: string
          description: the one who signed this block (bytes20)
        transactions:
          type: array
          description: IDs of transactions
          items:
            type: string
            description: ID of transaction (bytes32)
      example:
        number: 1
        id: '0x00000001c458949985a6d86b7139690b8811dd3b4647c02d4f41cdefb7d32327'
        size: 238
        parentID: '0x00000002a0c772179aa43cb6bb55d0b31369f9e92014c88a50b2cb99f9be1c5d'
        timestamp: 1523156271
        gasLimit: 10000000
        beneficiary: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
        gasUsed: 0
        totalScore: 101
        txsRoot: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'
        stateRoot: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'
        receiptsRoot: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'
        signer: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
        transactions:
          - '0x4de71f2d588aa8a1ea00fe8312d92966da424d9939a511fc0be81e65fad52af8'
    Clause:
      properties:
        to:
          type: string
          description: 'recipient of clause, null for contract deployment (bytes32)'
        value:
          type: string
          description: hex form of token to be transferred
        data:
          type: string
          description: input data (bytes)
      example:
        to: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
        value: '0x10'
        data: null
    Transaction:
      properties:
        id:
          type: string
          description: identifier of the transaction
        size:
          type: integer
          format: uint32
          description: byte size of the transaction that is RLP encoded
        chainTag:
          type: integer
          format: uint8
          description: last byte of genesis block ID
        nonce:
          type: string
        blockRef:
          type: string
          description: 8 bytes prefix of some block ID
        clauses:
          type: array
          items:
            $ref: '#/components/schemas/Clause'
        gasPriceCoef:
          type: integer
          format: uint8
          description: coefficient used to calculate the final gas price
        gas:
          type: integer
          format: uint64
          description: max amount of gas can be consumed to execute this transaction
        dependsOn:
          type: string
          description: >-
            ID of the transaction on which the current transaction depends
            (bytes32)
        signer:
          type: string
          description: 'the one who signed the transaction, aka. tx origin'
        blockID:
          type: string
          description: ID of the block which contains this transaction
        index:
          type: integer
          description: index of the transaction in the block containing it
      example:
        id: '0x4de71f2d588aa8a1ea00fe8312d92966da424d9939a511fc0be81e65fad52af8'
        size: 180
        chainTag: 1
        nonce: '0xd92966da424d9939'
        blockRef: '0x00000001511fc0be'
        clauses: []
        gasPriceCoef: 128
        gas: 21000
        dependsOn: null
        signer: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
        blockID: '0x00000001c458949985a6d86b7139690b8811dd3b4647c02d4f41cdefb7d32327'
        index: 0
    Log:
      properties:
        address:
          type: string
          description: the address of contract which produces the log (bytes20)
        topics:
          type: array
          items:
            type: string
        data:
          type: string
      example:
        address: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
        topics:
          - '0x4de71f2d588aa8a1ea00fe8312d92966da424d9939a511fc0be81e65fad52af8'
        data: '0xddff'
    Receipt:
      properties:
        gasUsed:
          type: integer
          format: uint64
        gasPayer:
          type: string
          description: address of account who payed used gas
        reward:
          type: string
          description: hex form of amount of reward
        reverted:
          type: boolean
          description: true means the transaction was reverted
        outputs:
          type: array
          items:
            properties:
              contractAddress:
                type: string
                description: >-
                  deployed contract address, if the corresponding clause is a
                  contract deployment clause
              logs:
                type: array
                items:
                  $ref: '#/components/schemas/Log'
      example:
        gasUsed: 21000
        gasPayer: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
        reward: '0x723daf2'
        reverted: false
        outputs: []
    ContractCall:
      properties:
        value:
          type: string
          description: amount of token to be transferred
        data:
          type: string
          description: input data for contract call
        gas:
          type: integer
          format: uint64
          description: 'optional, to specify max gas for execution'
        gasPrice:
          type: string
          description: 'optional, absolute gas price'
        caller:
          type: string
          description: 'optional, to specify the caller'
      example:
        value: '0x0'
        data: '0x5665436861696e2054686f72'
    ContractCallResult:
      properties:
        data:
          type: string
          description: the output data
        gasUsed:
          type: integer
          format: uint64
          description: gas used during execution
        reverted:
          type: boolean
        vmError:
          type: string
      example:
        data: '0x103556a73c10e38ffe2fc4aa50fc9d46ad0148f07e26417e117bd1ece9d948b5'
        gasUsed: 21000
        reverted: false
        vmError: ''
    Options:
      properties:
        offset:
          type: integer
        limit: 
          type: integer
        sort:
          type: integer
          enum:
            - 0
            - 1
    Range:
      properties:
        unit:
          type: string
          enum:
            - block
            - time
        from:
          type: integer
          format: uint64
        to:
          type: integer
          format: uint64
      example:
        unit: block
        from: 100
        to: 1000
    TopicSet:
      properties:
        topic0:
          type: string
        topic1:
          type: string
        topic2:
          type: string
        topic3:
          type: string
        topic4:
          type: string
      example:
        topic0: '0x103556a73c10e38ffe2fc4aa50fc9d46ad0148f07e26417e117bd1ece9d948b5'
    LogFilter:
      properties:
        range:
          $ref: '#/components/schemas/Range'
        options:
          $ref: '#/components/schemas/Options'
        topicSets:
          type: array
          items:
            $ref: '#/components/schemas/TopicSet'
    FilteredLog:
      properties:
        topics:
          type: array
          items:
            type: string
        data:
          type: string
        blockID:
          type: string
        blockNumber:
          type: integer
        blockTime:
          type: integer
        logIndex:
          type: integer
        txID:
          type: string
        txOrigin:
          type: string
      example:
        topics:
          - '0x4de71f2d588aa8a1ea00fe8312d92966da424d9939a511fc0be81e65fad52af8'
        data: '0x4de71f2d588aa8a1ea00fe8312d92966da424d9939a511fc0be81e65fad52af8'
        blockID: '0x00000001c458949985a6d86b7139690b8811dd3b4647c02d4f41cdefb7d32327'
        blockNumber: 1
        blockTime: 1523156271
        logIndex: 0
        txID: '0x4de71f2d588aa8a1ea00fe8312d92966da424d9939a511fc0be81e65fad52af8'
        txOrigin: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
  parameters:
    AddressInPath:
      name: address
      in: path
      description: address of account
      required: true
      schema:
        type: string
      example: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed'
    RevisionInQuery:
      name: revision
      in: query
      description: can be block number or ID. best block is assumed if omitted.
      schema:
        type: string
    RevisionInPath:
      name: revision
      in: path
      description: 'can be block number, ID or ''best'' for lastest block'
      required: true
      schema:
        type: string
      example: best
    StorageKeyInPath:
      in: path
      description: the key(position) to access account storage
      required: true
      name: key
      schema:
        type: string
      example: '0x0000000000000000000000000000000000000000000000000000000000000001'
    TxIDInPath:
      in: path
      description: ID of transaction
      required: true
      name: id
      schema:
        type: string
      example: '0x9bcc6526a76ae560244f698805cc001977246cb92c2b4f1e2b7a204e445409ea'
